class ArgParseHack(dict):
    def __getattr__(self,val):
        return self[val]

params = ArgParseHack({
    "augment": False,
    "batch_size": 20,
    "bidirectional": True,
    "checkpoint": False,
    "checkpoint_per_batch": 0,
    "continue_from": '',
    "cuda": False,
    "dist_backend": 'gloo',
    "dist_url": 'tcp"://127.0.0.1":1550',
    "epochs": 70,
    "finetune": False,
    "gpu_rank": None,
    "hidden_layers": 5,
    "hidden_size": 800,
    "id": 'Deepspeech training',
    "labels_path": 'labels.json',
    "log_dir": 'visualize/deepspeech_final',
    "log_params": False,
    "lr": 0.0003,
    "max_norm": 400,
    "momentum": 0.9,
    "no_sorta_grad": False,
    "noise_dir": None,
    "noise_min": 0.0,
    "noise_prob": 0.4,
    "num_workers": 4,
    "rank": 0,
    "rnn_type": 'gru',
    "sample_rate": 16000,
    "tensorboard": False,
    "train_manifest": 'data/train_manifest.csv',
    "val_manifest": 'data/val_manifest.csv',
    "visdom": False,
    "window": 'hamming',
    "window_size": 0.02,
    "window_stride": 0.01,
    "world_size": 1,
})
